table _Measures
	lineageTag: 975d9212-2005-40b5-a7c5-20ffe0e0f5f0

	measure Avg_Wait_Time = AVERAGE(Hospital_Data[patient_waittime])
		formatString: #,##0.00
		lineageTag: 17af517d-9b17-4dfc-bb39-d50070433b3f

	measure Avg_Sat_Score = AVERAGE(Hospital_Data[patient_sat_score])
		formatString: #,##0.00
		lineageTag: a17397f8-67ee-4cbe-a1d9-84891422b5d5

	measure Count_Unique_Patients = COUNTROWS(VALUES(Hospital_Data[patient_id]))
		formatString: #,0
		lineageTag: a6520891-9394-4158-98c7-feddf03946cf

	measure Count_Patients = COUNTROWS(VALUES(Hospital_Data))
		formatString: #,0
		lineageTag: df375e30-efb9-4949-bcd4-43b15b512f67

	measure Count_Patient_Visits =
			CALCULATE(
			    COUNTROWS(VALUES(Hospital_Data)),
			    ALLEXCEPT(Hospital_Data, Hospital_Data[patient_first_initial], Hospital_Data[patient_last_name])
			)
		formatString: #,0
		lineageTag: dcc3e9f1-e46e-4ab7-a94d-274e1d628904

	measure Avg_Age = AVERAGE(Hospital_Data[patient_age])
		formatString: #,##0.00
		lineageTag: 9b7610d6-e7ad-4844-9f96-0d42dcd28189

	measure Total_Visits =
			CALCULATE(
			    [Count_Patients],
			    ALL( Hospital_Data )
			)
		formatString: #,0
		lineageTag: 8394a0a0-c45d-4e7a-be3d-77be1ed8426a

	measure Percent_Of_Total_Visits =
			DIVIDE(
			    [Count_Patients],
			    [Total_Visits],
			    0
			)
		formatString: (#,##0.00 %)
		lineageTag: 8073f0be-ada5-4937-a5c4-68e3c3d781cd

	measure Select_Measure =
			SWITCH(
			    SELECTEDVALUE(Metrics[Metric]),
			    "Patient Count", [Count_Patients],
			    "Satisfaction Score", [Avg_Sat_Score],
			    "Wait Time", [Avg_Wait_Time]
			)
		lineageTag: b577f91e-6363-4835-b92b-48b09dedf861

		formatStringDefinition =
				SWITCH(
				    SELECTEDVALUE(Metrics[Metric]),
				    "Patient Count", "#,##0",
				    "Satisfaction Score", "#,##0.00",
				    "Wait Time", "#,##0.00"
				)

	measure SM_By_Weekday_And_Hour = SELECTEDVALUE(Metrics[Metric]) & " by Weekday and Hour"
		formatString: #,0
		displayFolder: _Formatting
		lineageTag: 9b6a9b0e-3b21-40c7-8553-fd18b27233c2

	measure SM_By_Dept = SELECTEDVALUE(Metrics[Metric]) & " by Department Referral"
		formatString: #,0
		displayFolder: _Formatting
		lineageTag: 86cc191c-b8d3-4920-b809-66c2a24405f8

	measure SM_By_Race = SELECTEDVALUE(Metrics[Metric]) & " by Patient Race"
		formatString: #,0
		displayFolder: _Formatting
		lineageTag: 01fc957b-0697-4a68-bc76-947945b71a6d

	measure SM_By_Aging_Bucket = SELECTEDVALUE(Metrics[Metric]) & " by Age Group"
		formatString: #,0
		displayFolder: _Formatting
		lineageTag: 7291f9f8-9f71-44b4-a096-e5eb9256e710

	measure Trend_Satisfaction = ```
			VAR Known = 
			FILTER (
			    SELECTCOLUMNS (
			        CALCULATETABLE( VALUES( Calendar[Date] ), ALLSELECTED( Calendar[Date] ) ),
			        "Known[X]", Calendar[Date],
			        "Known[Y]", [Avg_Sat_Score]
			    ),
			    NOT ( ISBLANK ( Known[X] ) ) &&
			    NOT ( ISBLANK ( Known[Y] ) )
			)
			
			VAR Count_Items =
			    COUNTROWS ( Known )
			VAR Sum_X =
			    SUMX ( Known, Known[X] )
			VAR Sum_X2 =
			    SUMX ( Known, Known[X] ^ 2 )
			VAR Sum_Y =
			    SUMX ( Known, Known[Y] )
			VAR Sum_Y2 =
			    SUMX ( Known, Known[Y] ^ 2 )
			VAR Sum_XY =
			    SUMX ( Known, Known[X] * Known[Y] )
			
			VAR Pearson_Numerator = Sum_XY - DIVIDE(Sum_X * Sum_Y, Count_Items)
			VAR Pearson_Denominator = SQRT((Sum_X2 - DIVIDE(Sum_X^2, Count_Items)) * (Sum_Y2 - DIVIDE(Sum_Y^2, Count_Items)))
			VAR Pearson_Correlation = DIVIDE(Pearson_Numerator, Pearson_Denominator)
			
			RETURN
			    Pearson_Correlation
			```
		displayFolder: _Trends
		lineageTag: a69d6caa-0900-47ef-adb0-4f0e702297ee

	measure Trend_Wait_Times = ```
			VAR Known = 
			FILTER (
			    SELECTCOLUMNS (
			        CALCULATETABLE( VALUES( Calendar[Date] ), ALLSELECTED( Calendar[Date] ) ),
			        "Known[X]", Calendar[Date],
			        "Known[Y]", [Avg_Wait_Time]
			    ),
			    NOT ( ISBLANK ( Known[X] ) ) &&
			    NOT ( ISBLANK ( Known[Y] ) )
			)
			
			VAR Count_Items =
			    COUNTROWS ( Known )
			VAR Sum_X =
			    SUMX ( Known, Known[X] )
			VAR Sum_X2 =
			    SUMX ( Known, Known[X] ^ 2 )
			VAR Sum_Y =
			    SUMX ( Known, Known[Y] )
			VAR Sum_Y2 =
			    SUMX ( Known, Known[Y] ^ 2 )
			VAR Sum_XY =
			    SUMX ( Known, Known[X] * Known[Y] )
			
			VAR Pearson_Numerator = Sum_XY - DIVIDE(Sum_X * Sum_Y, Count_Items)
			VAR Pearson_Denominator = SQRT((Sum_X2 - DIVIDE(Sum_X^2, Count_Items)) * (Sum_Y2 - DIVIDE(Sum_Y^2, Count_Items)))
			VAR Pearson_Correlation = DIVIDE(Pearson_Numerator, Pearson_Denominator)
			
			RETURN
			    Pearson_Correlation
			```
		displayFolder: _Trends
		lineageTag: 51d48501-3f29-481b-aeec-8df05bf632a8

	measure Trend_Patient_Count = ```
			VAR Known = 
			FILTER (
			    SELECTCOLUMNS (
			        CALCULATETABLE( VALUES( Calendar[Date] ), ALLSELECTED( Calendar[Date] ) ),
			        "Known[X]", Calendar[Date],
			        "Known[Y]", [Count_Patients]
			    ),
			    NOT ( ISBLANK ( Known[X] ) ) &&
			    NOT ( ISBLANK ( Known[Y] ) )
			)
			
			VAR Count_Items =
			    COUNTROWS ( Known )
			VAR Sum_X =
			    SUMX ( Known, Known[X] )
			VAR Sum_X2 =
			    SUMX ( Known, Known[X] ^ 2 )
			VAR Sum_Y =
			    SUMX ( Known, Known[Y] )
			VAR Sum_Y2 =
			    SUMX ( Known, Known[Y] ^ 2 )
			VAR Sum_XY =
			    SUMX ( Known, Known[X] * Known[Y] )
			
			VAR Pearson_Numerator = Sum_XY - DIVIDE(Sum_X * Sum_Y, Count_Items)
			VAR Pearson_Denominator = SQRT((Sum_X2 - DIVIDE(Sum_X^2, Count_Items)) * (Sum_Y2 - DIVIDE(Sum_Y^2, Count_Items)))
			VAR Pearson_Correlation = DIVIDE(Pearson_Numerator, Pearson_Denominator)
			
			RETURN
			    Pearson_Correlation
			```
		displayFolder: _Trends
		lineageTag: da9d1b21-fe0d-4c98-952a-1ec09bdf0831

	measure Trend_Line_Patient_Count = ```
			VAR Known =
			    FILTER (
			        SELECTCOLUMNS (
			            CALCULATETABLE ( VALUES ( Calendar[Date] ), ALLSELECTED (Calendar) ),
			            "Known[X]", Calendar[Date],
			            "Known[Y]", [Count_Patients]
			        ),
			        AND ( NOT ( ISBLANK ( Known[X] ) ), NOT ( ISBLANK ( Known[Y] ) ) )
			    )
			VAR Count_Items =
			    COUNTROWS ( Known )
			VAR Sum_X =
			    SUMX ( Known, Known[X] )
			VAR Sum_X2 =
			    SUMX ( Known, Known[X] ^ 2 )
			VAR Sum_Y =
			    SUMX ( Known, Known[Y] )
			VAR Sum_XY =
			    SUMX ( Known, Known[X] * Known[Y] )
			VAR Average_X =
			    AVERAGEX ( Known, Known[X] )
			VAR Average_Y =
			    AVERAGEX ( Known, Known[Y] )
			VAR Slope =
			    DIVIDE (
			        Count_Items * Sum_XY - Sum_X * Sum_Y,
			        Count_Items * Sum_X2 - Sum_X ^ 2
			    )
			VAR Intercept = Average_Y
			    - Slope * Average_X
			    
			VAR reg = 
			    SUMX ( 
			        DISTINCT ( Calendar[Date] ),
			        Intercept + Slope * Calendar[Date]
			    )
			
			RETURN
			    reg
			```
		displayFolder: _Trends
		lineageTag: 3d7d43eb-8b39-4c10-b30b-87d8dcb409df

	measure Trend_Line_Satisfaction = ```
			VAR Known =
			    FILTER (
			        SELECTCOLUMNS (
			            CALCULATETABLE ( VALUES ( Calendar[Date] ), ALLSELECTED (Calendar) ),
			            "Known[X]", Calendar[Date],
			            "Known[Y]", [Avg_Sat_Score]
			        ),
			        AND ( NOT ( ISBLANK ( Known[X] ) ), NOT ( ISBLANK ( Known[Y] ) ) )
			    )
			VAR Count_Items =
			    COUNTROWS ( Known )
			VAR Sum_X =
			    SUMX ( Known, Known[X] )
			VAR Sum_X2 =
			    SUMX ( Known, Known[X] ^ 2 )
			VAR Sum_Y =
			    SUMX ( Known, Known[Y] )
			VAR Sum_XY =
			    SUMX ( Known, Known[X] * Known[Y] )
			VAR Average_X =
			    AVERAGEX ( Known, Known[X] )
			VAR Average_Y =
			    AVERAGEX ( Known, Known[Y] )
			VAR Slope =
			    DIVIDE (
			        Count_Items * Sum_XY - Sum_X * Sum_Y,
			        Count_Items * Sum_X2 - Sum_X ^ 2
			    )
			VAR Intercept = Average_Y
			    - Slope * Average_X
			    
			VAR reg = 
			    SUMX ( 
			        DISTINCT ( Calendar[Date] ),
			        Intercept + Slope * Calendar[Date]
			    )
			
			RETURN
			    reg
			```
		displayFolder: _Trends
		lineageTag: fe56f0b2-780b-4a8f-88c5-6011223eaa27

	measure Trend_Line_Wait_Times = ```
			VAR Known =
			    FILTER (
			        SELECTCOLUMNS (
			            CALCULATETABLE ( VALUES ( Calendar[Date] ), ALLSELECTED (Calendar) ),
			            "Known[X]", Calendar[Date],
			            "Known[Y]", [Avg_Wait_Time]
			        ),
			        AND ( NOT ( ISBLANK ( Known[X] ) ), NOT ( ISBLANK ( Known[Y] ) ) )
			    )
			VAR Count_Items =
			    COUNTROWS ( Known )
			VAR Sum_X =
			    SUMX ( Known, Known[X] )
			VAR Sum_X2 =
			    SUMX ( Known, Known[X] ^ 2 )
			VAR Sum_Y =
			    SUMX ( Known, Known[Y] )
			VAR Sum_XY =
			    SUMX ( Known, Known[X] * Known[Y] )
			VAR Average_X =
			    AVERAGEX ( Known, Known[X] )
			VAR Average_Y =
			    AVERAGEX ( Known, Known[Y] )
			VAR Slope =
			    DIVIDE (
			        Count_Items * Sum_XY - Sum_X * Sum_Y,
			        Count_Items * Sum_X2 - Sum_X ^ 2
			    )
			VAR Intercept = Average_Y
			    - Slope * Average_X
			    
			VAR reg = 
			    SUMX ( 
			        DISTINCT ( Calendar[Date] ),
			        Intercept + Slope * Calendar[Date]
			    )
			
			RETURN
			    reg
			```
		displayFolder: _Trends
		lineageTag: a379eb5d-c97d-42b2-a33e-f843f4a88099

	measure Title_Trend_Patients = ```
			
			VAR direction = IF([Trend_Patient_Count] >= 0, "Up", "Down")
			
			RETURN 
			    "Patient Count (Trending " & direction & ")"
			```
		displayFolder: _Formatting
		lineageTag: 2613e0de-e16f-495e-aa34-8c72c3237096

	measure Title_Trend_Satisfaction = ```
			
			VAR direction = IF([Trend_Line_Satisfaction] >= 0, "Up", "Down")
			
			VAR avg_val = FORMAT( [Avg_Sat_Score], "#,##0.#0" )
			
			RETURN 
			    "Patient Satisfaction (Trending " & direction & ") - Avg: " & avg_val 
			```
		displayFolder: _Formatting
		lineageTag: aa434be1-3013-4577-9197-cdf41beb3409

	measure Title_Trend_Wait_Times = ```
			
			VAR direction = IF([Trend_Wait_Times] >= 0, "Up", "Down")
			
			VAR avg_val = FORMAT( [Avg_Wait_Time], "#,##0.#0" )
			
			RETURN 
			    "Patient Wait Times (Trending " & direction & ") - Avg: " & avg_val 
			```
		displayFolder: _Formatting
		lineageTag: ce2382d0-bb5d-4f37-8358-0e88cc8f7d33

	measure Title_Trend_Select = ```
			
			VAR metric = SELECTEDVALUE(Metrics[Metric])
			
			VAR trend_score = 
			    SWITCH(
			        metric,
			        "Satisfaction Score", [Trend_Satisfaction],
			        "Wait Time", [Trend_Wait_Times],
			        "Patient Count", [Trend_Patient_Count]
			    )
			
			VAR direction = IF(trend_score >= 0, "Up", "Down")
			
			VAR output = 
			    SWITCH(
			        metric,
			        "Satisfaction Score", metric & " (Trending " & direction & ") - Avg: " & FORMAT( [Avg_Sat_Score], "#,##0.#0" ) ,
			        "Wait Time", metric & " (Trending " & direction & ") - Avg: " & FORMAT( [Avg_Wait_Time], "#,##0.#0" ) ,
			        "Patient Count", metric & " (Trending " & direction & ")"
			    )
			
			RETURN 
			    output
			```
		displayFolder: _Formatting
		lineageTag: 082b2ba7-74c2-431d-aa7b-1069a5c8fa22

	measure Spacing = "......."
		displayFolder: _Formatting
		lineageTag: 628d8827-3f74-4181-a19a-b770ae9f3025

	measure Title_SM = SELECTEDVALUE(Metrics[Metric])
		formatString: #,0
		displayFolder: _Formatting
		lineageTag: 106071e6-126a-439b-ae8b-2d4f0f9d8749

	measure Title_Avg_Patient_Age = ```
			
			VAR avg_val = FORMAT( [Avg_Age], "#,##0" )
			
			RETURN 
			    "Patient Age Distribution (Average: " & avg_val & ")"
			```
		formatString: #,0
		displayFolder: _Formatting
		lineageTag: b1c4aee9-5b30-45d7-a701-815c63e577d6

	measure Title_Avg_Satisfaction = ```
			
			VAR avg_val = FORMAT( [Avg_Sat_Score], "#,##0.#0" )
			
			RETURN 
			    "Patient Satisfaction Scores (Average: " & avg_val & ")"
			```
		displayFolder: _Formatting
		lineageTag: b59f306d-384e-4f75-8968-c4bd3feb202b

	measure Title_Avg_Wait_Times = ```
			
			VAR avg_val = FORMAT( [Avg_Wait_Time], "#,##0.##" )
			
			RETURN 
			    "Patient Wait Times (Average: " & avg_val & ")"
			```
		displayFolder: _Formatting
		lineageTag: 9f91dc5a-3eb4-4374-b904-aa8f393f25b4

	measure Sat_Score_Admit =
			CALCULATE(
			    [Avg_Sat_Score],
			    Hospital_Data[patient_admitted_desc] = "Admitted"
			)
		displayFolder: _Explicit
		lineageTag: 3076c54f-1f06-4aff-9131-bdd802f2df91

	measure Sat_Score_NonAdmit =
			CALCULATE(
			    [Avg_Sat_Score],
			    Hospital_Data[patient_admitted_desc] = "Not Admitted"
			)
		displayFolder: _Explicit
		lineageTag: 5d9c4436-abb6-4818-8541-308989405416

	measure Wait_Admit =
			CALCULATE(
			    [Avg_Wait_Time],
			    Hospital_Data[patient_admitted_desc] = "Admitted"
			)
		displayFolder: _Explicit
		lineageTag: 9624f3a7-09fc-4ad6-ab60-154c3562b471

	measure Wait_NonAdmit =
			CALCULATE(
			    [Avg_Wait_Time],
			    Hospital_Data[patient_admitted_desc] = "Not Admitted"
			)
		displayFolder: _Explicit
		lineageTag: 1c79ef10-bb60-417a-ac64-7bfe8d24ec69

	measure PY_Avg_Age =
			CALCULATE(
			    [Avg_Age],
			    DATEADD( Calendar[Date], - 1, YEAR )
			)
		formatString: #,##0.0
		displayFolder: _TimeIntelligence
		lineageTag: e69c94f4-612e-453e-bc07-9fa0e4d1198b

	measure PY_Avg_Sat =
			CALCULATE(
			    [Avg_Sat_Score],
			    DATEADD( Calendar[Date], - 1, YEAR )
			)
		formatString: #,##0.00
		displayFolder: _TimeIntelligence
		lineageTag: f1c3dd5f-db8a-4743-9948-c4bee75add2e

	measure PY_Patients =
			CALCULATE(
			    [Count_Patients],
			    DATEADD( Calendar[Date], - 1, YEAR )
			)
		formatString: #,##0
		displayFolder: _TimeIntelligence
		lineageTag: c5a94d90-156e-41f6-ad41-3161a9bb8eae

	measure YoY_Avg_Age = [Avg_Age] - [PY_Avg_Age]
		formatString: #,##0.00
		displayFolder: _TimeIntelligence
		lineageTag: 1ae9074d-1a06-4e6e-9b2e-29b5dbe87d9b

	measure YoY_Avg_Sat = [Avg_Sat_Score] - [PY_Avg_Sat]
		formatString: #,##0.00
		displayFolder: _TimeIntelligence
		lineageTag: 444cd1dd-fea4-4ad8-a535-9e7ff643231c

	measure YoY_Patients = [Count_Patients] - [PY_Patients]
		formatString: #,##0
		displayFolder: _TimeIntelligence
		lineageTag: f59fdc34-d092-4a5b-ba6d-68b277813a38

	measure PY_Select_Measure =
			CALCULATE(
			    [Select_Measure],
			    DATEADD( Calendar[Date], - 1, YEAR )
			)
		displayFolder: _TimeIntelligence
		lineageTag: e2796995-fdd2-4b1f-a593-9e2915be7a91

		formatStringDefinition =
				SWITCH(
				    SELECTEDVALUE(Metrics[Metric]),
				    "Patient Count", "#,##0",
				    "Satisfaction Score", "#,##0.00",
				    "Wait Time", "#,##0.00"
				)

	measure PY_Wait_Time =
			CALCULATE(
			    [Avg_Wait_Time],
			    DATEADD( Calendar[Date], - 1, YEAR )
			)
		formatString: #,##0.0
		displayFolder: _TimeIntelligence
		lineageTag: 8e18aeb8-7a24-4809-972c-843ac1506f49

	measure YoY_Wait_Time = [Avg_Wait_Time] - [PY_Wait_Time]
		formatString: #,##0.0
		displayFolder: _TimeIntelligence
		lineageTag: 21972a41-32e7-42c8-b683-4b5cb236bbeb

	measure YoY_Select_Measure = [Select_Measure] - [PY_Select_Measure]
		displayFolder: _TimeIntelligence
		lineageTag: 0ebf65c4-1451-4158-abbf-881f5ac640bb

		formatStringDefinition =
				SWITCH(
				    SELECTEDVALUE(Metrics[Metric]),
				    "Patient Count", "#,##0",
				    "Satisfaction Score", "#,##0.00",
				    "Wait Time", "#,##0.00"
				)

	measure Title_YoY_Department = ```
			
			VAR metric = SELECTEDVALUE(Metrics[Metric])
			
			RETURN 
			    metric & " (YoY) By Department"
			```
		displayFolder: _Formatting
		lineageTag: 35c045a8-7f03-4866-9b78-595df2a6f765

	measure Title_YoY_Age = ```
			
			VAR metric = SELECTEDVALUE(Metrics[Metric])
			
			RETURN 
			    metric & " (YoY) By Age"
			```
		displayFolder: _Formatting
		lineageTag: 57a47b38-7530-4058-8221-4daf21a5ce95

	measure Title_YoY_Race = ```
			
			VAR metric = SELECTEDVALUE(Metrics[Metric])
			
			RETURN 
			    metric & " (YoY) By Patient Race"
			```
		displayFolder: _Formatting
		lineageTag: b002e883-1dfc-4a6f-9ab3-556e7a7040a2

	measure Title_Compared_to_PY = ```
			
			VAR metric = SELECTEDVALUE(Metrics[Metric])
			
			RETURN 
			    metric & " Compared to Prior Year"
			```
		displayFolder: _Formatting
		lineageTag: 864d1c2a-ab61-4d66-a3b7-46df7a7abfe6

	measure Title_Trend_Select_No_Avg = ```
			
			VAR metric = SELECTEDVALUE(Metrics[Metric])
			
			VAR trend_score = 
			    SWITCH(
			        metric,
			        "Satisfaction Score", [Trend_Satisfaction],
			        "Wait Time", [Trend_Wait_Times],
			        "Patient Count", [Trend_Patient_Count]
			    )
			
			VAR direction = IF(trend_score >= 0, "Up", "Down")
			
			VAR output = 
			    SWITCH(
			        metric,
			        "Satisfaction Score", metric & " (Trending " & direction & ")",
			        "Wait Time", metric & " (Trending " & direction & ")",
			        "Patient Count", metric & " (Trending " & direction & ")"
			    )
			
			RETURN 
			    output
			```
		displayFolder: _Formatting
		lineageTag: a37b5d68-4b7b-4665-bfff-4eaec2352c15

	measure Title_YoY_Admit = ```
			
			VAR metric = SELECTEDVALUE(Metrics[Metric])
			
			RETURN 
			    metric & " (YoY) By Patient Admit Status"
			```
		displayFolder: _Formatting
		lineageTag: fb379a53-f378-412c-8e0f-a51bc05ae96c

	measure Title_YoY_Gender = ```
			
			VAR metric = SELECTEDVALUE(Metrics[Metric])
			
			RETURN 
			    metric & " (YoY) By Gender"
			```
		displayFolder: _Formatting
		lineageTag: 0cd56938-25db-46d3-a6c7-8c2948042283

	measure YoY_%_Avg_Sat =
			DIVIDE(
			    [YoY_Avg_Sat],
			    [PY_Avg_Sat],
			    0
			)
		formatString: #,##0.00 %
		displayFolder: _TimeIntelligence
		lineageTag: adf26e28-c78f-484e-8198-755b6e54dac3

	measure Title_Admit = ```
			
			VAR metric = SELECTEDVALUE(Metrics[Metric])
			
			RETURN 
			    metric & " By Patient Admit Status"
			```
		displayFolder: _Formatting
		lineageTag: 891455ba-52d5-466b-9b94-04f9ae495054

	measure Title_Age = ```
			
			VAR metric = SELECTEDVALUE(Metrics[Metric])
			
			RETURN 
			    metric & " By Age"
			```
		displayFolder: _Formatting
		lineageTag: 2afefb21-cf3f-47f4-93ed-6315ca764b6b

	measure Title_Department = ```
			
			VAR metric = SELECTEDVALUE(Metrics[Metric])
			
			RETURN 
			    metric & " By Department"
			```
		displayFolder: _Formatting
		lineageTag: af34cfa4-af81-4e8c-9f30-4e830a291da7

	measure Title_Gender = ```
			
			VAR metric = SELECTEDVALUE(Metrics[Metric])
			
			RETURN 
			    metric & " By Gender"
			```
		displayFolder: _Formatting
		lineageTag: f652e024-3ddd-4220-a80b-066dfca23bd6

	measure Title_Race = ```
			
			VAR metric = SELECTEDVALUE(Metrics[Metric])
			
			RETURN 
			    metric & " By Patient Race"
			```
		displayFolder: _Formatting
		lineageTag: 5f4f1f1b-d372-4856-8ff9-b4fd266af049

	measure SM_By_Gender_And_Admit = SELECTEDVALUE(Metrics[Metric]) & " by Admit Status and Gender"
		formatString: #,0
		displayFolder: _Formatting
		lineageTag: d32b47b1-72ba-4b83-8ec3-63c6baf73971

	measure Title_YoY_Gender_Admit = ```
			
			VAR metric = SELECTEDVALUE(Metrics[Metric])
			
			RETURN 
			    metric & " (YoY) By Admit Status and Gender"
			```
		displayFolder: _Formatting
		lineageTag: b0fca535-3546-4f06-a769-338889e4431c

	measure Title_Trend_Select_With_PY = ```
			
			VAR metric = SELECTEDVALUE(Metrics[Metric])
			
			VAR trend_score = 
			    SWITCH(
			        metric,
			        "Satisfaction Score", [Trend_Satisfaction],
			        "Wait Time", [Trend_Wait_Times],
			        "Patient Count", [Trend_Patient_Count]
			    )
			
			VAR direction = IF(trend_score >= 0, "Up", "Down")
			
			VAR output = 
			    SWITCH(
			        metric,
			        "Satisfaction Score", metric & " With PY (Trending " & direction & ")",
			        "Wait Time", metric & " With PY (Trending " & direction & ")",
			        "Patient Count", metric & " With PY (Trending " & direction & ")"
			    )
			
			RETURN 
			    output
			```
		displayFolder: _Formatting
		lineageTag: 9c7c4546-f7ac-40e4-844d-c96d5889cf7e

	measure SM_By_Dim = SELECTEDVALUE(Metrics[Metric]) & " by " & [Selected_Dimension]
		formatString: #,0
		displayFolder: _Formatting
		lineageTag: 4b61005b-4db1-499f-b90f-a01307f0507f

	measure Test_Measure = 1
		formatString: 0
		lineageTag: 746f5194-c999-466b-b940-7e52b0ca45bd

	measure sel = SELECTEDVALUE(__Dimensions[Dimensions])
		lineageTag: 363c2bb4-f3cf-4b96-8901-20a6df43e8f6

	measure Total_Wait_Time = SUM('Hospital_Data'[patient_waittime])
		formatString: 0
		lineageTag: 3fbf6b38-d7d8-48d9-8c9e-028b46fc7619

	measure 'CY Patient Count' = [Count_Patients]
		formatString: 0
		displayFolder: __TI Testing
		lineageTag: 8229b170-c084-438e-afc1-9aabe51be903

	measure 'PY Patient Count' =
			
			CALCULATE(
			    [Count_Patients],
			    DATEADD(Calendar[Date], -1, YEAR)
			)
		formatString: 0
		displayFolder: __TI Testing
		lineageTag: 2cec9ea3-d9d2-443e-b870-550f32bc875b

	measure 'CY YTD Patient Count' =
			
			CALCULATE(
			    [Count_Patients],
			    DATESYTD( Calendar[Date] )
			)
		formatString: 0
		displayFolder: __TI Testing
		lineageTag: 1d76ebbc-7661-4ab8-b3a9-bfd6716813c2

	measure 'PY YTD Patient Count' =
			
			CALCULATE(
			    [Count_Patients],
			    DATESYTD( DATEADD( Calendar[Date], - 1, YEAR ) )
			)
		formatString: 0
		displayFolder: __TI Testing
		lineageTag: 3c32cc8e-f125-4cfd-8214-1075a030af4b

	measure _measurekiller_test_measure = [SM_By_Dept]
		displayFolder: _Formatting
		lineageTag: 17657104-8542-4dda-9db2-cdf9d0356675

	column Column1
		dataType: string
		isHidden
		lineageTag: 64c43d5c-bbbb-4494-8d70-f033efb05424
		summarizeBy: none
		sourceColumn: Column1

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	partition _Measures = m
		mode: import
		source =
				let
				    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText("i44FAA==", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [Column1 = _t]),
				    #"Changed Type" = Table.TransformColumnTypes(Source,{{"Column1", type text}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table

