table Calendar
	lineageTag: c6ec0662-83e1-4856-9430-5543e4d5130a

	column Date
		dataType: dateTime
		formatString: Short Date
		lineageTag: f1180430-f52b-4b50-9f76-6bceeac81adb
		summarizeBy: none
		sourceColumn: Date

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column Month
		dataType: int64
		formatString: 0
		lineageTag: 7f31b975-f96e-4348-87a9-2120f3540673
		summarizeBy: none
		sourceColumn: Month

		annotation SummarizationSetBy = Automatic

	column Month_Year
		dataType: string
		lineageTag: 6db208b0-2b05-4ab0-9063-ff950d66db9e
		summarizeBy: none
		sourceColumn: Month_Year
		sortByColumn: Month_Year_Sort

		changedProperty = SortByColumn

		annotation SummarizationSetBy = Automatic

	column Week_End_Date
		dataType: dateTime
		formatString: Long Date
		lineageTag: 83664e2b-38bc-4971-9abc-2434547c1cfe
		summarizeBy: none
		sourceColumn: Week_End_Date

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column Qtr_ID
		dataType: int64
		formatString: 0
		lineageTag: 0f1ae444-428d-4096-933e-845c0487221f
		summarizeBy: none
		sourceColumn: Qtr_ID

		annotation SummarizationSetBy = Automatic

	column Qtr_Desc
		dataType: string
		lineageTag: 18ccf059-db41-4f45-a674-7295f1586351
		summarizeBy: none
		sourceColumn: Qtr_Desc

		annotation SummarizationSetBy = Automatic

	column Weekday
		dataType: string
		lineageTag: dba85bf3-09fd-45b5-89b0-9b49360dde09
		summarizeBy: none
		sourceColumn: Weekday
		sortByColumn: Weekday_Sort

		changedProperty = SortByColumn

		annotation SummarizationSetBy = Automatic

	column Weekday_Sort
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: 2fd32f9f-66c1-4c76-966d-b67177cd30e9
		summarizeBy: none
		sourceColumn: Weekday_Sort

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column _ = 0
		formatString: 0
		lineageTag: 175e8019-92cc-443c-81e6-32c55b19e530
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column Month_Year_Sort
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: 8038e463-9ed2-45f1-903a-47029babc79c
		summarizeBy: none
		sourceColumn: Month_Year_Sort

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Year
		dataType: int64
		formatString: 0
		lineageTag: 40896b8b-4625-4cd4-b910-c92ab99117c1
		summarizeBy: none
		sourceColumn: Year

		annotation SummarizationSetBy = Automatic

	partition Calendar = m
		mode: import
		source = ```
				let
				    // Get Min and Max dates from Hospital Data date column
				    MinDate = List.Min(Hospital_Data[Date]),
				    MaxDate = List.Max(Hospital_Data[Date]),
				
				    // Create list of dates using the min as the start, max as the end
				    DateList = List.Dates(
				        MinDate,
				        Duration.Days(MaxDate - MinDate) + 1,
				        #duration(1, 0, 0, 0)
				    ),
				    
				    // Create Date Table from DateList
				    DateTable = Table.FromList(DateList, Splitter.SplitByNothing()),
				    #"Renamed Columns" = Table.RenameColumns(DateTable, {{"Column1", "Date"}}),
				    #"Changed Type" = Table.TransformColumnTypes(#"Renamed Columns", {{"Date", type date}}),
				    #"Inserted Month" = Table.AddColumn(#"Changed Type", "Month", each Date.Month([Date]), Int64.Type),
				
				    // Inserted Month Yeear (March 2023)
				    #"Inserted Month Name" = Table.AddColumn(#"Inserted Month", "Month_Year", each Date.MonthName([Date]) & " " & Text.From(Date.Year([Date])), type text),
				    #"Inserted End of Week" = Table.AddColumn(#"Inserted Month Name", "Week_End_Date", each Date.EndOfWeek([Date]), type date),
				    #"Inserted Quarter1" = Table.AddColumn(#"Inserted End of Week", "Qtr_ID", each Date.QuarterOfYear([Date]), Int64.Type),
				    #"Inserted Quarter" = Table.AddColumn(#"Inserted Quarter1", "Qtr_Desc", each "Q" & Text.From(Date.QuarterOfYear([Date])) & " " & Text.From(Date.Year([Date])), type text),
				    #"Inserted Day Name" = Table.AddColumn(#"Inserted Quarter", "Weekday", each Date.DayOfWeekName([Date]), type text),
				    #"Inserted Day of Week" = Table.AddColumn(#"Inserted Day Name", "Weekday_Sort", each Date.DayOfWeek([Date]), Int64.Type),
				    #"Added Custom Column" = Table.AddColumn(#"Inserted Day of Week", "Custom", each Text.Combine({Date.ToText([Date], "yyyy"), Date.ToText([Date], "MM")}), type text),
				    #"Renamed Columns1" = Table.RenameColumns(#"Added Custom Column",{{"Custom", "Month_Year_Sort"}}),
				    #"Changed Type1" = Table.TransformColumnTypes(#"Renamed Columns1",{{"Month_Year_Sort", Int64.Type}}),
				    #"Inserted Year" = Table.AddColumn(#"Changed Type1", "Year", each Date.Year([Date]), Int64.Type)
				in
				    #"Inserted Year"
				```

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

