{
  "compatibilityLevel": 1601,
  "model": {
    "annotations": [
      {
        "name": "__PBI_TimeIntelligenceEnabled",
        "value": "0"
      },
      {
        "name": "PBI_QueryOrder",
        "value": "[\"Hospital_Data\",\"Calendar\",\"Time_Of_Day\",\"_Measures\",\"Metrics\"]"
      },
      {
        "name": "__TEdtr",
        "value": "1"
      },
      {
        "name": "PBI_ProTooling",
        "value": "[\"CalcGroup\",\"DevMode\"]"
      }
    ],
    "culture": "en-US",
    "cultures": [
      {
        "name": "en-US",
        "linguisticMetadata": {}
      }
    ],
    "dataAccessOptions": {
      "legacyRedirects": true,
      "returnErrorValuesAsNull": true
    },
    "defaultPowerBIDataSourceVersion": "powerBI_V3",
    "discourageImplicitMeasures": true,
    "relationships": [
      {
        "name": "045a58ce-861a-02ba-8ee3-52eb3f2427c2",
        "fromColumn": "Date",
        "fromTable": "Hospital_Data",
        "toColumn": "Date",
        "toTable": "Calendar"
      },
      {
        "name": "f5a8fab7-1b7b-3d13-5e68-26de63a0b698",
        "fromColumn": "Time",
        "fromTable": "Hospital_Data",
        "toColumn": "Time_Of_Day",
        "toTable": "Time_Of_Day"
      }
    ],
    "roles": [
      {
        "name": "Departments",
        "annotations": [
          {
            "name": "PBI_Id",
            "value": "cb57acda6dce4a6bb73c755defc435a9"
          }
        ],
        "modelPermission": "read",
        "tablePermissions": [
          {
            "name": "Hospital_Data",
            "filterExpression": [
              "SWITCH(",
              "    USERPRINCIPALNAME(),",
              "    \"csantoleri@eigenx.com\", [department_referral] = \"Cardiology\",",
              "    \"rcinelli@eigenx.com\", TRUE, // [department_referral] = \"General Practice\",",
              "    \"acooper@eigenx.com\", TRUE,",
              "    TRUE ",
              ")"
            ]
          }
        ]
      }
    ],
    "sourceQueryCulture": "en-US",
    "tables": [
      {
        "name": "Hospital_Data",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "patient_id",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "4d6d1b0c-0edc-4767-8926-debe099b9ee3",
            "sourceColumn": "patient_id",
            "summarizeBy": "none"
          },
          {
            "name": "patient_gender",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "07bbaa84-680b-4dd6-98c7-72d1e41dc09e",
            "sourceColumn": "patient_gender",
            "summarizeBy": "none"
          },
          {
            "name": "patient_age",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "5dd89b50-1b93-4717-85c1-34ec13b7576e",
            "sourceColumn": "patient_age",
            "summarizeBy": "sum"
          },
          {
            "name": "patient_first_initial",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "d1747439-ae76-4404-9776-1dc28cad882c",
            "sourceColumn": "patient_first_initial",
            "summarizeBy": "none"
          },
          {
            "name": "patient_last_name",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "fe0592e2-5378-45de-8f7c-08f7f9168744",
            "sourceColumn": "patient_last_name",
            "summarizeBy": "none"
          },
          {
            "name": "patient_race",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "61d23a31-e8bc-495d-8919-e2001de91330",
            "sourceColumn": "patient_race",
            "summarizeBy": "none"
          },
          {
            "name": "department_referral",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "aae1ebbe-4fed-41b1-8b6b-69d6748962ce",
            "sourceColumn": "department_referral",
            "summarizeBy": "none"
          },
          {
            "name": "patient_waittime",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "f746aec8-2ea3-42b3-85b1-5f5a8076fa80",
            "sourceColumn": "patient_waittime",
            "summarizeBy": "sum"
          },
          {
            "name": "patient_sat_score",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "f5161046-8dab-44a9-964c-bc0c122e48ca",
            "sourceColumn": "patient_sat_score",
            "summarizeBy": "sum"
          },
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Short Date",
            "lineageTag": "94379af4-1e3d-4ac6-be70-488346229a00",
            "sourceColumn": "Date",
            "summarizeBy": "none"
          },
          {
            "name": "Time",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Time"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Time",
            "lineageTag": "5be88afc-32a2-4af6-9a1b-48fab05559f2",
            "sourceColumn": "Time",
            "summarizeBy": "none"
          },
          {
            "name": "Age_Bucket",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "expression": [
              "",
              "SWITCH(",
              "    TRUE(),",
              "    [patient_age] < 18, \"Pediatric (0 - 17)\",",
              "    [patient_age] >= 18 && [patient_age] < 35, \"Young Adults (18 - 34)\",",
              "    [patient_age] >= 35 && [patient_age] < 50, \"Midlife Adults (35 - 49)\",",
              "    [patient_age] >= 50 && [patient_age] < 65, \"Pre-Senior (50 - 64)\",",
              "    \"Senior Citizen (65+)\"",
              ")"
            ],
            "isDataTypeInferred": true,
            "lineageTag": "fc171415-dc4b-45cd-a5cc-b60a82d101d3",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "patient_admitted_desc",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "e8d1b7f0-ad10-46a2-8759-a441559c400a",
            "sourceColumn": "patient_admitted_desc",
            "summarizeBy": "none"
          },
          {
            "name": "Wait_Time_Bucket",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "SortByColumn"
              }
            ],
            "dataType": "string",
            "expression": [
              "",
              "SWITCH(",
              "    TRUE(),",
              "    [patient_waittime] <= 15, \"0 - 15 Minutes\",",
              "    [patient_waittime] >= 16 && [patient_waittime] <= 30, \"16 - 30 Minutes\",",
              "    [patient_waittime] >= 31 && [patient_waittime] <= 45, \"31 - 45 Minutes\",",
              "    [patient_waittime] >= 46 && [patient_waittime] <= 60, \"46 - 60 Minutes\",",
              "    \"Over 60 Minutes\"",
              ")"
            ],
            "isDataTypeInferred": true,
            "lineageTag": "22f5e3fe-e51e-489d-8349-15e4d9be677c",
            "sortByColumn": "Wait_Time_Bucket_Sort",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Wait_Time_Bucket_Sort",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "int64",
            "expression": [
              "",
              "SWITCH(",
              "    TRUE(),",
              "    [patient_waittime] <= 15, 0,",
              "    [patient_waittime] >= 15 && [patient_waittime] <= 30, 1,",
              "    [patient_waittime] >= 31 && [patient_waittime] <= 45, 2,",
              "    [patient_waittime] >= 46 && [patient_waittime] <= 60, 3,",
              "    4",
              ")"
            ],
            "formatString": "0",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "f8273df3-fb87-49d3-86b6-d6c7c58d2ef9",
            "summarizeBy": "sum",
            "type": "calculated"
          },
          {
            "name": "Satisfaction_Bucket",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "SortByColumn"
              }
            ],
            "dataType": "string",
            "expression": [
              "",
              "SWITCH(",
              "    TRUE(),",
              "    ROUND([patient_sat_score], 0) <= 1, \"0 - 1\",",
              "    ROUND([patient_sat_score], 0) >= 2 && ROUND([patient_sat_score], 0) <= 3, \"2 - 3\",",
              "    ROUND([patient_sat_score], 0) >= 4 && ROUND([patient_sat_score], 0) <= 5, \"4 - 5\",",
              "    ROUND([patient_sat_score], 0) >= 6 && ROUND([patient_sat_score], 0) <= 7, \"6 - 7\",",
              "    ROUND([patient_sat_score], 0) >= 8 && ROUND([patient_sat_score], 0) <= 9, \"8 - 9\",",
              "    \"10\"",
              ")"
            ],
            "isDataTypeInferred": true,
            "lineageTag": "87bd6a6e-884e-40df-a0c4-76ef1d68a95f",
            "sortByColumn": "Satisfaction_Bucket_Sort",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Satisfaction_Bucket_Sort",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "int64",
            "expression": [
              "",
              "SWITCH(",
              "    TRUE(),",
              "    ROUND([patient_sat_score], 0) <= 1, 0,",
              "    ROUND([patient_sat_score], 0) >= 2 && ROUND([patient_sat_score], 0) <= 3, 1,",
              "    ROUND([patient_sat_score], 0) >= 4 && ROUND([patient_sat_score], 0) <= 5, 2,",
              "    ROUND([patient_sat_score], 0) >= 6 && ROUND([patient_sat_score], 0) <= 7, 3,",
              "    ROUND([patient_sat_score], 0) >= 8 && ROUND([patient_sat_score], 0) <= 9, 4,",
              "    5",
              ")"
            ],
            "formatString": "0",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "5c9ef5a9-cab4-43cd-89e9-f5ef9325d019",
            "summarizeBy": "sum",
            "type": "calculated"
          },
          {
            "name": "DateTime",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "dateTime",
            "formatString": "General Date",
            "lineageTag": "5435c90b-5c9a-4956-82b0-d40a4df8d8fb",
            "sourceColumn": "DateTime",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "b57bf411-a147-451f-9e11-8f8a07b05169",
        "partitions": [
          {
            "name": "Hospital_Data",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Csv.Document(File.Contents(\"C:\\Users\\AndrewCooper\\OneDrive - Eigen X LLC\\PBI\\Hospital Dashboard\\Hospital_ER_Data_20240826.csv\"),[Delimiter=\",\", Columns=13, Encoding=1252, QuoteStyle=QuoteStyle.None]),",
                "    #\"Promoted Headers\" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(#\"Promoted Headers\",{{\"Date & Time\", type datetime}, {\"Hour_of_day\", Int64.Type}, {\"patient_id\", type text}, {\"patient_gender\", type text}, {\"patient_age\", Int64.Type}, {\"patient_first_initial\", type text}, {\"patient_last_name\", type text}, {\"patient_race\", type text}, {\"department_referral\", type text}, {\"month\", Int64.Type}, {\"patient_admin_flag\", type logical}, {\"patient_waittime\", Int64.Type}, {\"patient_sat_score\", type number}}),",
                "    #\"Inserted Date\" = Table.AddColumn(#\"Changed Type\", \"Date\", each DateTime.Date([#\"Date & Time\"]), type date),",
                "    #\"Inserted Time\" = Table.AddColumn(#\"Inserted Date\", \"Time\", each DateTime.Time([#\"Date & Time\"]), type time),",
                "    #\"Removed Columns\" = Table.RemoveColumns(#\"Inserted Time\",{\"month\", \"Hour_of_day\"}),",
                "    #\"Reordered Columns\" = Table.ReorderColumns(#\"Removed Columns\",{\"Date\", \"Time\", \"patient_id\", \"patient_gender\", \"patient_age\", \"patient_first_initial\", \"patient_last_name\", \"patient_race\", \"department_referral\", \"patient_admin_flag\", \"patient_waittime\", \"patient_sat_score\"}),",
                "    #\"Renamed Columns\" = Table.RenameColumns(#\"Reordered Columns\",{{\"patient_admin_flag\", \"patient_admitted\"}, {\"Date & Time\", \"DateTime\"}}),",
                "    #\"Added Conditional Column\" = Table.AddColumn(#\"Renamed Columns\", \"patient_admitted_desc\", each if [patient_admitted] = true then \"Admitted\" else \"Not Admitted\", type text),",
                "    #\"Removed Columns1\" = Table.RemoveColumns(#\"Added Conditional Column\",{\"patient_admitted\"}),",
                "    #\"Replaced Value\" = Table.ReplaceValue(#\"Removed Columns1\",\"M\",\"Male\",Replacer.ReplaceValue,{\"patient_gender\"}),",
                "    #\"Replaced Value1\" = Table.ReplaceValue(#\"Replaced Value\",\"F\",\"Female\",Replacer.ReplaceValue,{\"patient_gender\"})",
                "in",
                "    #\"Replaced Value1\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "Calendar",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Short Date",
            "lineageTag": "f1180430-f52b-4b50-9f76-6bceeac81adb",
            "sourceColumn": "Date",
            "summarizeBy": "none"
          },
          {
            "name": "Month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "7f31b975-f96e-4348-87a9-2120f3540673",
            "sourceColumn": "Month",
            "summarizeBy": "none"
          },
          {
            "name": "Month_Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "SortByColumn"
              }
            ],
            "dataType": "string",
            "lineageTag": "6db208b0-2b05-4ab0-9063-ff950d66db9e",
            "sortByColumn": "Month_Year_Sort",
            "sourceColumn": "Month_Year",
            "summarizeBy": "none"
          },
          {
            "name": "Week_End_Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Date",
            "lineageTag": "83664e2b-38bc-4971-9abc-2434547c1cfe",
            "sourceColumn": "Week_End_Date",
            "summarizeBy": "none"
          },
          {
            "name": "Qtr_ID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "0f1ae444-428d-4096-933e-845c0487221f",
            "sourceColumn": "Qtr_ID",
            "summarizeBy": "none"
          },
          {
            "name": "Qtr_Desc",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "18ccf059-db41-4f45-a674-7295f1586351",
            "sourceColumn": "Qtr_Desc",
            "summarizeBy": "none"
          },
          {
            "name": "Weekday",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "SortByColumn"
              }
            ],
            "dataType": "string",
            "lineageTag": "dba85bf3-09fd-45b5-89b0-9b49360dde09",
            "sortByColumn": "Weekday_Sort",
            "sourceColumn": "Weekday",
            "summarizeBy": "none"
          },
          {
            "name": "Weekday_Sort",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "2fd32f9f-66c1-4c76-966d-b67177cd30e9",
            "sourceColumn": "Weekday_Sort",
            "summarizeBy": "none"
          },
          {
            "name": "_",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "expression": "0",
            "formatString": "0",
            "isDataTypeInferred": true,
            "lineageTag": "175e8019-92cc-443c-81e6-32c55b19e530",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Month_Year_Sort",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "8038e463-9ed2-45f1-903a-47029babc79c",
            "sourceColumn": "Month_Year_Sort",
            "summarizeBy": "none"
          },
          {
            "name": "Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "40896b8b-4625-4cd4-b910-c92ab99117c1",
            "sourceColumn": "Year",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "c6ec0662-83e1-4856-9430-5543e4d5130a",
        "partitions": [
          {
            "name": "Calendar",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    // Get Min and Max dates from Hospital Data date column",
                "    MinDate = List.Min(Hospital_Data[Date]),",
                "    MaxDate = List.Max(Hospital_Data[Date]),",
                "",
                "    // Create list of dates using the min as the start, max as the end",
                "    DateList = List.Dates(",
                "        MinDate,",
                "        Duration.Days(MaxDate - MinDate) + 1,",
                "        #duration(1, 0, 0, 0)",
                "    ),",
                "    ",
                "    // Create Date Table from DateList",
                "    DateTable = Table.FromList(DateList, Splitter.SplitByNothing()),",
                "    #\"Renamed Columns\" = Table.RenameColumns(DateTable, {{\"Column1\", \"Date\"}}),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(#\"Renamed Columns\", {{\"Date\", type date}}),",
                "    #\"Inserted Month\" = Table.AddColumn(#\"Changed Type\", \"Month\", each Date.Month([Date]), Int64.Type),",
                "",
                "    // Inserted Month Yeear (March 2023)",
                "    #\"Inserted Month Name\" = Table.AddColumn(#\"Inserted Month\", \"Month_Year\", each Date.MonthName([Date]) & \" \" & Text.From(Date.Year([Date])), type text),",
                "    #\"Inserted End of Week\" = Table.AddColumn(#\"Inserted Month Name\", \"Week_End_Date\", each Date.EndOfWeek([Date]), type date),",
                "    #\"Inserted Quarter1\" = Table.AddColumn(#\"Inserted End of Week\", \"Qtr_ID\", each Date.QuarterOfYear([Date]), Int64.Type),",
                "    #\"Inserted Quarter\" = Table.AddColumn(#\"Inserted Quarter1\", \"Qtr_Desc\", each \"Q\" & Text.From(Date.QuarterOfYear([Date])) & \" \" & Text.From(Date.Year([Date])), type text),",
                "    #\"Inserted Day Name\" = Table.AddColumn(#\"Inserted Quarter\", \"Weekday\", each Date.DayOfWeekName([Date]), type text),",
                "    #\"Inserted Day of Week\" = Table.AddColumn(#\"Inserted Day Name\", \"Weekday_Sort\", each Date.DayOfWeek([Date]), Int64.Type),",
                "    #\"Added Custom Column\" = Table.AddColumn(#\"Inserted Day of Week\", \"Custom\", each Text.Combine({Date.ToText([Date], \"yyyy\"), Date.ToText([Date], \"MM\")}), type text),",
                "    #\"Renamed Columns1\" = Table.RenameColumns(#\"Added Custom Column\",{{\"Custom\", \"Month_Year_Sort\"}}),",
                "    #\"Changed Type1\" = Table.TransformColumnTypes(#\"Renamed Columns1\",{{\"Month_Year_Sort\", Int64.Type}}),",
                "    #\"Inserted Year\" = Table.AddColumn(#\"Changed Type1\", \"Year\", each Date.Year([Date]), Int64.Type)",
                "in",
                "    #\"Inserted Year\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "Time_Of_Day",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "Time_Of_Day",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Time"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Time",
            "lineageTag": "e20351dd-2c62-4bca-a40f-347281e30179",
            "sourceColumn": "Time_Of_Day",
            "summarizeBy": "none"
          },
          {
            "name": "Hour",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "ee52ff11-7353-4d75-a91a-e3484976d479",
            "sourceColumn": "Hour",
            "summarizeBy": "none"
          },
          {
            "name": "Time_Bucket",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "f6264fff-7eac-4e32-ab68-f2acbd3a226b",
            "sourceColumn": "Time_Bucket",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "d1619ac6-ae2f-4653-b7f3-a1857d7ddcbe",
        "partitions": [
          {
            "name": "Time_Of_Day",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    // Define the start time",
                "    StartTime = #time(0, 0, 0),",
                "    ",
                "    // Calculate the total minutes in a 24-hour period (1440 minutes)",
                "    TotalMinutes = 1440,",
                "    ",
                "    // Create a list of times, increasing by one minute",
                "    TimeList = List.Times(StartTime, TotalMinutes, #duration(0, 0, 1, 0)),",
                "    ",
                "    // Convert the list to a table",
                "    TimeTable = Table.FromList(TimeList, Splitter.SplitByNothing()),",
                "    ",
                "    // Rename the column",
                "    #\"Renamed Columns\" = Table.RenameColumns(TimeTable, {{\"Column1\", \"Time\"}}),",
                "    ",
                "    // Change the column type to time",
                "    #\"Changed Type\" = Table.TransformColumnTypes(#\"Renamed Columns\", {{\"Time\", type time}}),",
                "    #\"Renamed Columns1\" = Table.RenameColumns(#\"Changed Type\",{{\"Time\", \"Time_Of_Day\"}}),",
                "    #\"Inserted Hour\" = Table.AddColumn(#\"Renamed Columns1\", \"Hour\", each Time.Hour([Time_Of_Day]), Int64.Type),",
                "    #\"Added Custom\" = Table.AddColumn(#\"Inserted Hour\", \"Time_Bucket\", each if [Hour] < 8 then \"Morning\"",
                "else if [Hour] >= 8 and [Hour] < 16 then \"Afternoon\"",
                "else \"Night\")",
                "in",
                "    #\"Added Custom\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "_Measures",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "Column1",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "64c43d5c-bbbb-4494-8d70-f033efb05424",
            "sourceColumn": "Column1",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "975d9212-2005-40b5-a7c5-20ffe0e0f5f0",
        "measures": [
          {
            "name": "Avg_Wait_Time",
            "expression": "AVERAGE(Hospital_Data[patient_waittime])",
            "formatString": "#,##0.00",
            "lineageTag": "17af517d-9b17-4dfc-bb39-d50070433b3f"
          },
          {
            "name": "Avg_Sat_Score",
            "expression": "AVERAGE(Hospital_Data[patient_sat_score])",
            "formatString": "#,##0.00",
            "lineageTag": "a17397f8-67ee-4cbe-a1d9-84891422b5d5"
          },
          {
            "name": "Count_Unique_Patients",
            "expression": "COUNTROWS(VALUES(Hospital_Data[patient_id]))",
            "formatString": "#,0",
            "lineageTag": "a6520891-9394-4158-98c7-feddf03946cf"
          },
          {
            "name": "Count_Patients",
            "expression": "COUNTROWS(VALUES(Hospital_Data))",
            "formatString": "#,0",
            "lineageTag": "df375e30-efb9-4949-bcd4-43b15b512f67"
          },
          {
            "name": "Count_Patient_Visits",
            "expression": [
              "CALCULATE(",
              "    COUNTROWS(VALUES(Hospital_Data)),",
              "    ALLEXCEPT(Hospital_Data, Hospital_Data[patient_first_initial], Hospital_Data[patient_last_name])",
              ")"
            ],
            "formatString": "#,0",
            "lineageTag": "dcc3e9f1-e46e-4ab7-a94d-274e1d628904"
          },
          {
            "name": "Avg_Age",
            "expression": "AVERAGE(Hospital_Data[patient_age])",
            "formatString": "#,##0.00",
            "lineageTag": "9b7610d6-e7ad-4844-9f96-0d42dcd28189"
          },
          {
            "name": "Total_Visits",
            "expression": [
              "CALCULATE(",
              "    [Count_Patients],",
              "    ALL( Hospital_Data )",
              ")"
            ],
            "formatString": "#,0",
            "lineageTag": "8394a0a0-c45d-4e7a-be3d-77be1ed8426a"
          },
          {
            "name": "Percent_Of_Total_Visits",
            "expression": [
              "DIVIDE(",
              "    [Count_Patients],",
              "    [Total_Visits],",
              "    0",
              ")"
            ],
            "formatString": "(#,##0.00 %)",
            "lineageTag": "8073f0be-ada5-4937-a5c4-68e3c3d781cd"
          },
          {
            "name": "Select_Measure",
            "expression": [
              "SWITCH(",
              "    SELECTEDVALUE(Metrics[Metric]),",
              "    \"Patient Count\", [Count_Patients],",
              "    \"Satisfaction Score\", [Avg_Sat_Score],",
              "    \"Wait Time\", [Avg_Wait_Time]",
              ")"
            ],
            "formatStringDefinition": {
              "expression": [
                "SWITCH(",
                "    SELECTEDVALUE(Metrics[Metric]),",
                "    \"Patient Count\", \"#,##0\",",
                "    \"Satisfaction Score\", \"#,##0.00\",",
                "    \"Wait Time\", \"#,##0.00\"",
                ")"
              ]
            },
            "lineageTag": "b577f91e-6363-4835-b92b-48b09dedf861"
          },
          {
            "name": "SM_By_Weekday_And_Hour",
            "displayFolder": "_Formatting",
            "expression": "SELECTEDVALUE(Metrics[Metric]) & \" by Weekday and Hour\"",
            "formatString": "#,0",
            "lineageTag": "9b6a9b0e-3b21-40c7-8553-fd18b27233c2"
          },
          {
            "name": "SM_By_Dept",
            "displayFolder": "_Formatting",
            "expression": "SELECTEDVALUE(Metrics[Metric]) & \" by Department Referral\"",
            "formatString": "#,0",
            "lineageTag": "86cc191c-b8d3-4920-b809-66c2a24405f8"
          },
          {
            "name": "SM_By_Race",
            "displayFolder": "_Formatting",
            "expression": "SELECTEDVALUE(Metrics[Metric]) & \" by Patient Race\"",
            "formatString": "#,0",
            "lineageTag": "01fc957b-0697-4a68-bc76-947945b71a6d"
          },
          {
            "name": "SM_By_Aging_Bucket",
            "displayFolder": "_Formatting",
            "expression": "SELECTEDVALUE(Metrics[Metric]) & \" by Age Group\"",
            "formatString": "#,0",
            "lineageTag": "7291f9f8-9f71-44b4-a096-e5eb9256e710"
          },
          {
            "name": "Trend_Satisfaction",
            "displayFolder": "_Trends",
            "expression": [
              "VAR Known = ",
              "FILTER (",
              "    SELECTCOLUMNS (",
              "        CALCULATETABLE( VALUES( Calendar[Date] ), ALLSELECTED( Calendar[Date] ) ),",
              "        \"Known[X]\", Calendar[Date],",
              "        \"Known[Y]\", [Avg_Sat_Score]",
              "    ),",
              "    NOT ( ISBLANK ( Known[X] ) ) &&",
              "    NOT ( ISBLANK ( Known[Y] ) )",
              ")",
              "",
              "VAR Count_Items =",
              "    COUNTROWS ( Known )",
              "VAR Sum_X =",
              "    SUMX ( Known, Known[X] )",
              "VAR Sum_X2 =",
              "    SUMX ( Known, Known[X] ^ 2 )",
              "VAR Sum_Y =",
              "    SUMX ( Known, Known[Y] )",
              "VAR Sum_Y2 =",
              "    SUMX ( Known, Known[Y] ^ 2 )",
              "VAR Sum_XY =",
              "    SUMX ( Known, Known[X] * Known[Y] )",
              "",
              "VAR Pearson_Numerator = Sum_XY - DIVIDE(Sum_X * Sum_Y, Count_Items)",
              "VAR Pearson_Denominator = SQRT((Sum_X2 - DIVIDE(Sum_X^2, Count_Items)) * (Sum_Y2 - DIVIDE(Sum_Y^2, Count_Items)))",
              "VAR Pearson_Correlation = DIVIDE(Pearson_Numerator, Pearson_Denominator)",
              "",
              "RETURN",
              "    Pearson_Correlation"
            ],
            "lineageTag": "a69d6caa-0900-47ef-adb0-4f0e702297ee"
          },
          {
            "name": "Trend_Wait_Times",
            "displayFolder": "_Trends",
            "expression": [
              "VAR Known = ",
              "FILTER (",
              "    SELECTCOLUMNS (",
              "        CALCULATETABLE( VALUES( Calendar[Date] ), ALLSELECTED( Calendar[Date] ) ),",
              "        \"Known[X]\", Calendar[Date],",
              "        \"Known[Y]\", [Avg_Wait_Time]",
              "    ),",
              "    NOT ( ISBLANK ( Known[X] ) ) &&",
              "    NOT ( ISBLANK ( Known[Y] ) )",
              ")",
              "",
              "VAR Count_Items =",
              "    COUNTROWS ( Known )",
              "VAR Sum_X =",
              "    SUMX ( Known, Known[X] )",
              "VAR Sum_X2 =",
              "    SUMX ( Known, Known[X] ^ 2 )",
              "VAR Sum_Y =",
              "    SUMX ( Known, Known[Y] )",
              "VAR Sum_Y2 =",
              "    SUMX ( Known, Known[Y] ^ 2 )",
              "VAR Sum_XY =",
              "    SUMX ( Known, Known[X] * Known[Y] )",
              "",
              "VAR Pearson_Numerator = Sum_XY - DIVIDE(Sum_X * Sum_Y, Count_Items)",
              "VAR Pearson_Denominator = SQRT((Sum_X2 - DIVIDE(Sum_X^2, Count_Items)) * (Sum_Y2 - DIVIDE(Sum_Y^2, Count_Items)))",
              "VAR Pearson_Correlation = DIVIDE(Pearson_Numerator, Pearson_Denominator)",
              "",
              "RETURN",
              "    Pearson_Correlation"
            ],
            "lineageTag": "51d48501-3f29-481b-aeec-8df05bf632a8"
          },
          {
            "name": "Trend_Patient_Count",
            "displayFolder": "_Trends",
            "expression": [
              "VAR Known = ",
              "FILTER (",
              "    SELECTCOLUMNS (",
              "        CALCULATETABLE( VALUES( Calendar[Date] ), ALLSELECTED( Calendar[Date] ) ),",
              "        \"Known[X]\", Calendar[Date],",
              "        \"Known[Y]\", [Count_Patients]",
              "    ),",
              "    NOT ( ISBLANK ( Known[X] ) ) &&",
              "    NOT ( ISBLANK ( Known[Y] ) )",
              ")",
              "",
              "VAR Count_Items =",
              "    COUNTROWS ( Known )",
              "VAR Sum_X =",
              "    SUMX ( Known, Known[X] )",
              "VAR Sum_X2 =",
              "    SUMX ( Known, Known[X] ^ 2 )",
              "VAR Sum_Y =",
              "    SUMX ( Known, Known[Y] )",
              "VAR Sum_Y2 =",
              "    SUMX ( Known, Known[Y] ^ 2 )",
              "VAR Sum_XY =",
              "    SUMX ( Known, Known[X] * Known[Y] )",
              "",
              "VAR Pearson_Numerator = Sum_XY - DIVIDE(Sum_X * Sum_Y, Count_Items)",
              "VAR Pearson_Denominator = SQRT((Sum_X2 - DIVIDE(Sum_X^2, Count_Items)) * (Sum_Y2 - DIVIDE(Sum_Y^2, Count_Items)))",
              "VAR Pearson_Correlation = DIVIDE(Pearson_Numerator, Pearson_Denominator)",
              "",
              "RETURN",
              "    Pearson_Correlation"
            ],
            "lineageTag": "da9d1b21-fe0d-4c98-952a-1ec09bdf0831"
          },
          {
            "name": "Trend_Line_Patient_Count",
            "displayFolder": "_Trends",
            "expression": [
              "VAR Known =",
              "    FILTER (",
              "        SELECTCOLUMNS (",
              "            CALCULATETABLE ( VALUES ( Calendar[Date] ), ALLSELECTED (Calendar) ),",
              "            \"Known[X]\", Calendar[Date],",
              "            \"Known[Y]\", [Count_Patients]",
              "        ),",
              "        AND ( NOT ( ISBLANK ( Known[X] ) ), NOT ( ISBLANK ( Known[Y] ) ) )",
              "    )",
              "VAR Count_Items =",
              "    COUNTROWS ( Known )",
              "VAR Sum_X =",
              "    SUMX ( Known, Known[X] )",
              "VAR Sum_X2 =",
              "    SUMX ( Known, Known[X] ^ 2 )",
              "VAR Sum_Y =",
              "    SUMX ( Known, Known[Y] )",
              "VAR Sum_XY =",
              "    SUMX ( Known, Known[X] * Known[Y] )",
              "VAR Average_X =",
              "    AVERAGEX ( Known, Known[X] )",
              "VAR Average_Y =",
              "    AVERAGEX ( Known, Known[Y] )",
              "VAR Slope =",
              "    DIVIDE (",
              "        Count_Items * Sum_XY - Sum_X * Sum_Y,",
              "        Count_Items * Sum_X2 - Sum_X ^ 2",
              "    )",
              "VAR Intercept = Average_Y",
              "    - Slope * Average_X",
              "    ",
              "VAR reg = ",
              "    SUMX ( ",
              "        DISTINCT ( Calendar[Date] ),",
              "        Intercept + Slope * Calendar[Date]",
              "    )",
              "",
              "RETURN",
              "    reg"
            ],
            "lineageTag": "3d7d43eb-8b39-4c10-b30b-87d8dcb409df"
          },
          {
            "name": "Trend_Line_Satisfaction",
            "displayFolder": "_Trends",
            "expression": [
              "VAR Known =",
              "    FILTER (",
              "        SELECTCOLUMNS (",
              "            CALCULATETABLE ( VALUES ( Calendar[Date] ), ALLSELECTED (Calendar) ),",
              "            \"Known[X]\", Calendar[Date],",
              "            \"Known[Y]\", [Avg_Sat_Score]",
              "        ),",
              "        AND ( NOT ( ISBLANK ( Known[X] ) ), NOT ( ISBLANK ( Known[Y] ) ) )",
              "    )",
              "VAR Count_Items =",
              "    COUNTROWS ( Known )",
              "VAR Sum_X =",
              "    SUMX ( Known, Known[X] )",
              "VAR Sum_X2 =",
              "    SUMX ( Known, Known[X] ^ 2 )",
              "VAR Sum_Y =",
              "    SUMX ( Known, Known[Y] )",
              "VAR Sum_XY =",
              "    SUMX ( Known, Known[X] * Known[Y] )",
              "VAR Average_X =",
              "    AVERAGEX ( Known, Known[X] )",
              "VAR Average_Y =",
              "    AVERAGEX ( Known, Known[Y] )",
              "VAR Slope =",
              "    DIVIDE (",
              "        Count_Items * Sum_XY - Sum_X * Sum_Y,",
              "        Count_Items * Sum_X2 - Sum_X ^ 2",
              "    )",
              "VAR Intercept = Average_Y",
              "    - Slope * Average_X",
              "    ",
              "VAR reg = ",
              "    SUMX ( ",
              "        DISTINCT ( Calendar[Date] ),",
              "        Intercept + Slope * Calendar[Date]",
              "    )",
              "",
              "RETURN",
              "    reg"
            ],
            "lineageTag": "fe56f0b2-780b-4a8f-88c5-6011223eaa27"
          },
          {
            "name": "Trend_Line_Wait_Times",
            "displayFolder": "_Trends",
            "expression": [
              "VAR Known =",
              "    FILTER (",
              "        SELECTCOLUMNS (",
              "            CALCULATETABLE ( VALUES ( Calendar[Date] ), ALLSELECTED (Calendar) ),",
              "            \"Known[X]\", Calendar[Date],",
              "            \"Known[Y]\", [Avg_Wait_Time]",
              "        ),",
              "        AND ( NOT ( ISBLANK ( Known[X] ) ), NOT ( ISBLANK ( Known[Y] ) ) )",
              "    )",
              "VAR Count_Items =",
              "    COUNTROWS ( Known )",
              "VAR Sum_X =",
              "    SUMX ( Known, Known[X] )",
              "VAR Sum_X2 =",
              "    SUMX ( Known, Known[X] ^ 2 )",
              "VAR Sum_Y =",
              "    SUMX ( Known, Known[Y] )",
              "VAR Sum_XY =",
              "    SUMX ( Known, Known[X] * Known[Y] )",
              "VAR Average_X =",
              "    AVERAGEX ( Known, Known[X] )",
              "VAR Average_Y =",
              "    AVERAGEX ( Known, Known[Y] )",
              "VAR Slope =",
              "    DIVIDE (",
              "        Count_Items * Sum_XY - Sum_X * Sum_Y,",
              "        Count_Items * Sum_X2 - Sum_X ^ 2",
              "    )",
              "VAR Intercept = Average_Y",
              "    - Slope * Average_X",
              "    ",
              "VAR reg = ",
              "    SUMX ( ",
              "        DISTINCT ( Calendar[Date] ),",
              "        Intercept + Slope * Calendar[Date]",
              "    )",
              "",
              "RETURN",
              "    reg"
            ],
            "lineageTag": "a379eb5d-c97d-42b2-a33e-f843f4a88099"
          },
          {
            "name": "Title_Trend_Patients",
            "displayFolder": "_Formatting",
            "expression": [
              "",
              "VAR direction = IF([Trend_Patient_Count] >= 0, \"Up\", \"Down\")",
              "",
              "RETURN ",
              "    \"Patient Count (Trending \" & direction & \")\""
            ],
            "lineageTag": "2613e0de-e16f-495e-aa34-8c72c3237096"
          },
          {
            "name": "Title_Trend_Satisfaction",
            "displayFolder": "_Formatting",
            "expression": [
              "",
              "VAR direction = IF([Trend_Line_Satisfaction] >= 0, \"Up\", \"Down\")",
              "",
              "VAR avg_val = FORMAT( [Avg_Sat_Score], \"#,##0.#0\" )",
              "",
              "RETURN ",
              "    \"Patient Satisfaction (Trending \" & direction & \") - Avg: \" & avg_val "
            ],
            "lineageTag": "aa434be1-3013-4577-9197-cdf41beb3409"
          },
          {
            "name": "Title_Trend_Wait_Times",
            "displayFolder": "_Formatting",
            "expression": [
              "",
              "VAR direction = IF([Trend_Wait_Times] >= 0, \"Up\", \"Down\")",
              "",
              "VAR avg_val = FORMAT( [Avg_Wait_Time], \"#,##0.#0\" )",
              "",
              "RETURN ",
              "    \"Patient Wait Times (Trending \" & direction & \") - Avg: \" & avg_val "
            ],
            "lineageTag": "ce2382d0-bb5d-4f37-8358-0e88cc8f7d33"
          },
          {
            "name": "Title_Trend_Select",
            "displayFolder": "_Formatting",
            "expression": [
              "",
              "VAR metric = SELECTEDVALUE(Metrics[Metric])",
              "",
              "VAR trend_score = ",
              "    SWITCH(",
              "        metric,",
              "        \"Satisfaction Score\", [Trend_Satisfaction],",
              "        \"Wait Time\", [Trend_Wait_Times],",
              "        \"Patient Count\", [Trend_Patient_Count]",
              "    )",
              "",
              "VAR direction = IF(trend_score >= 0, \"Up\", \"Down\")",
              "",
              "VAR output = ",
              "    SWITCH(",
              "        metric,",
              "        \"Satisfaction Score\", metric & \" (Trending \" & direction & \") - Avg: \" & FORMAT( [Avg_Sat_Score], \"#,##0.#0\" ) ,",
              "        \"Wait Time\", metric & \" (Trending \" & direction & \") - Avg: \" & FORMAT( [Avg_Wait_Time], \"#,##0.#0\" ) ,",
              "        \"Patient Count\", metric & \" (Trending \" & direction & \")\"",
              "    )",
              "",
              "RETURN ",
              "    output"
            ],
            "lineageTag": "082b2ba7-74c2-431d-aa7b-1069a5c8fa22"
          },
          {
            "name": "Spacing",
            "displayFolder": "_Formatting",
            "expression": "\".......\"",
            "lineageTag": "628d8827-3f74-4181-a19a-b770ae9f3025"
          },
          {
            "name": "Title_SM",
            "displayFolder": "_Formatting",
            "expression": "SELECTEDVALUE(Metrics[Metric])",
            "formatString": "#,0",
            "lineageTag": "106071e6-126a-439b-ae8b-2d4f0f9d8749"
          },
          {
            "name": "Title_Avg_Patient_Age",
            "displayFolder": "_Formatting",
            "expression": [
              "",
              "VAR avg_val = FORMAT( [Avg_Age], \"#,##0\" )",
              "",
              "RETURN ",
              "    \"Patient Age Distribution (Average: \" & avg_val & \")\""
            ],
            "formatString": "#,0",
            "lineageTag": "b1c4aee9-5b30-45d7-a701-815c63e577d6"
          },
          {
            "name": "Title_Avg_Satisfaction",
            "displayFolder": "_Formatting",
            "expression": [
              "",
              "VAR avg_val = FORMAT( [Avg_Sat_Score], \"#,##0.#0\" )",
              "",
              "RETURN ",
              "    \"Patient Satisfaction Scores (Average: \" & avg_val & \")\""
            ],
            "lineageTag": "b59f306d-384e-4f75-8968-c4bd3feb202b"
          },
          {
            "name": "Title_Avg_Wait_Times",
            "displayFolder": "_Formatting",
            "expression": [
              "",
              "VAR avg_val = FORMAT( [Avg_Wait_Time], \"#,##0.##\" )",
              "",
              "RETURN ",
              "    \"Patient Wait Times (Average: \" & avg_val & \")\""
            ],
            "lineageTag": "9f91dc5a-3eb4-4374-b904-aa8f393f25b4"
          },
          {
            "name": "Sat_Score_Admit",
            "displayFolder": "_Explicit",
            "expression": [
              "CALCULATE(",
              "    [Avg_Sat_Score],",
              "    Hospital_Data[patient_admitted_desc] = \"Admitted\"",
              ")"
            ],
            "lineageTag": "3076c54f-1f06-4aff-9131-bdd802f2df91"
          },
          {
            "name": "Sat_Score_NonAdmit",
            "displayFolder": "_Explicit",
            "expression": [
              "CALCULATE(",
              "    [Avg_Sat_Score],",
              "    Hospital_Data[patient_admitted_desc] = \"Not Admitted\"",
              ")"
            ],
            "lineageTag": "5d9c4436-abb6-4818-8541-308989405416"
          },
          {
            "name": "Wait_Admit",
            "displayFolder": "_Explicit",
            "expression": [
              "CALCULATE(",
              "    [Avg_Wait_Time],",
              "    Hospital_Data[patient_admitted_desc] = \"Admitted\"",
              ")"
            ],
            "lineageTag": "9624f3a7-09fc-4ad6-ab60-154c3562b471"
          },
          {
            "name": "Wait_NonAdmit",
            "displayFolder": "_Explicit",
            "expression": [
              "CALCULATE(",
              "    [Avg_Wait_Time],",
              "    Hospital_Data[patient_admitted_desc] = \"Not Admitted\"",
              ")"
            ],
            "lineageTag": "1c79ef10-bb60-417a-ac64-7bfe8d24ec69"
          },
          {
            "name": "PY_Avg_Age",
            "displayFolder": "_TimeIntelligence",
            "expression": [
              "CALCULATE(",
              "    [Avg_Age],",
              "    DATEADD( Calendar[Date], - 1, YEAR )",
              ")"
            ],
            "formatString": "#,##0.0",
            "lineageTag": "e69c94f4-612e-453e-bc07-9fa0e4d1198b"
          },
          {
            "name": "PY_Avg_Sat",
            "displayFolder": "_TimeIntelligence",
            "expression": [
              "CALCULATE(",
              "    [Avg_Sat_Score],",
              "    DATEADD( Calendar[Date], - 1, YEAR )",
              ")"
            ],
            "formatString": "#,##0.00",
            "lineageTag": "f1c3dd5f-db8a-4743-9948-c4bee75add2e"
          },
          {
            "name": "PY_Patients",
            "displayFolder": "_TimeIntelligence",
            "expression": [
              "CALCULATE(",
              "    [Count_Patients],",
              "    DATEADD( Calendar[Date], - 1, YEAR )",
              ")"
            ],
            "formatString": "#,##0",
            "lineageTag": "c5a94d90-156e-41f6-ad41-3161a9bb8eae"
          },
          {
            "name": "YoY_Avg_Age",
            "displayFolder": "_TimeIntelligence",
            "expression": "[Avg_Age] - [PY_Avg_Age]",
            "formatString": "#,##0.00",
            "lineageTag": "1ae9074d-1a06-4e6e-9b2e-29b5dbe87d9b"
          },
          {
            "name": "YoY_Avg_Sat",
            "displayFolder": "_TimeIntelligence",
            "expression": "[Avg_Sat_Score] - [PY_Avg_Sat]",
            "formatString": "#,##0.00",
            "lineageTag": "444cd1dd-fea4-4ad8-a535-9e7ff643231c"
          },
          {
            "name": "YoY_Patients",
            "displayFolder": "_TimeIntelligence",
            "expression": "[Count_Patients] - [PY_Patients]",
            "formatString": "#,##0",
            "lineageTag": "f59fdc34-d092-4a5b-ba6d-68b277813a38"
          },
          {
            "name": "PY_Select_Measure",
            "displayFolder": "_TimeIntelligence",
            "expression": [
              "CALCULATE(",
              "    [Select_Measure],",
              "    DATEADD( Calendar[Date], - 1, YEAR )",
              ")"
            ],
            "formatStringDefinition": {
              "expression": [
                "SWITCH(",
                "    SELECTEDVALUE(Metrics[Metric]),",
                "    \"Patient Count\", \"#,##0\",",
                "    \"Satisfaction Score\", \"#,##0.00\",",
                "    \"Wait Time\", \"#,##0.00\"",
                ")"
              ]
            },
            "lineageTag": "e2796995-fdd2-4b1f-a593-9e2915be7a91"
          },
          {
            "name": "PY_Wait_Time",
            "displayFolder": "_TimeIntelligence",
            "expression": [
              "CALCULATE(",
              "    [Avg_Wait_Time],",
              "    DATEADD( Calendar[Date], - 1, YEAR )",
              ")"
            ],
            "formatString": "#,##0.0",
            "lineageTag": "8e18aeb8-7a24-4809-972c-843ac1506f49"
          },
          {
            "name": "YoY_Wait_Time",
            "displayFolder": "_TimeIntelligence",
            "expression": "[Avg_Wait_Time] - [PY_Wait_Time]",
            "formatString": "#,##0.0",
            "lineageTag": "21972a41-32e7-42c8-b683-4b5cb236bbeb"
          },
          {
            "name": "YoY_Select_Measure",
            "displayFolder": "_TimeIntelligence",
            "expression": "[Select_Measure] - [PY_Select_Measure]",
            "formatStringDefinition": {
              "expression": [
                "SWITCH(",
                "    SELECTEDVALUE(Metrics[Metric]),",
                "    \"Patient Count\", \"#,##0\",",
                "    \"Satisfaction Score\", \"#,##0.00\",",
                "    \"Wait Time\", \"#,##0.00\"",
                ")"
              ]
            },
            "lineageTag": "0ebf65c4-1451-4158-abbf-881f5ac640bb"
          },
          {
            "name": "Title_YoY_Department",
            "displayFolder": "_Formatting",
            "expression": [
              "",
              "VAR metric = SELECTEDVALUE(Metrics[Metric])",
              "",
              "RETURN ",
              "    metric & \" (YoY) By Department\""
            ],
            "lineageTag": "35c045a8-7f03-4866-9b78-595df2a6f765"
          },
          {
            "name": "Title_YoY_Age",
            "displayFolder": "_Formatting",
            "expression": [
              "",
              "VAR metric = SELECTEDVALUE(Metrics[Metric])",
              "",
              "RETURN ",
              "    metric & \" (YoY) By Age\""
            ],
            "lineageTag": "57a47b38-7530-4058-8221-4daf21a5ce95"
          },
          {
            "name": "Title_YoY_Race",
            "displayFolder": "_Formatting",
            "expression": [
              "",
              "VAR metric = SELECTEDVALUE(Metrics[Metric])",
              "",
              "RETURN ",
              "    metric & \" (YoY) By Patient Race\""
            ],
            "lineageTag": "b002e883-1dfc-4a6f-9ab3-556e7a7040a2"
          },
          {
            "name": "Title_Compared_to_PY",
            "displayFolder": "_Formatting",
            "expression": [
              "",
              "VAR metric = SELECTEDVALUE(Metrics[Metric])",
              "",
              "RETURN ",
              "    metric & \" Compared to Prior Year\""
            ],
            "lineageTag": "864d1c2a-ab61-4d66-a3b7-46df7a7abfe6"
          },
          {
            "name": "Title_Trend_Select_No_Avg",
            "displayFolder": "_Formatting",
            "expression": [
              "",
              "VAR metric = SELECTEDVALUE(Metrics[Metric])",
              "",
              "VAR trend_score = ",
              "    SWITCH(",
              "        metric,",
              "        \"Satisfaction Score\", [Trend_Satisfaction],",
              "        \"Wait Time\", [Trend_Wait_Times],",
              "        \"Patient Count\", [Trend_Patient_Count]",
              "    )",
              "",
              "VAR direction = IF(trend_score >= 0, \"Up\", \"Down\")",
              "",
              "VAR output = ",
              "    SWITCH(",
              "        metric,",
              "        \"Satisfaction Score\", metric & \" (Trending \" & direction & \")\",",
              "        \"Wait Time\", metric & \" (Trending \" & direction & \")\",",
              "        \"Patient Count\", metric & \" (Trending \" & direction & \")\"",
              "    )",
              "",
              "RETURN ",
              "    output"
            ],
            "lineageTag": "a37b5d68-4b7b-4665-bfff-4eaec2352c15"
          },
          {
            "name": "Title_YoY_Admit",
            "displayFolder": "_Formatting",
            "expression": [
              "",
              "VAR metric = SELECTEDVALUE(Metrics[Metric])",
              "",
              "RETURN ",
              "    metric & \" (YoY) By Patient Admit Status\""
            ],
            "lineageTag": "fb379a53-f378-412c-8e0f-a51bc05ae96c"
          },
          {
            "name": "Title_YoY_Gender",
            "displayFolder": "_Formatting",
            "expression": [
              "",
              "VAR metric = SELECTEDVALUE(Metrics[Metric])",
              "",
              "RETURN ",
              "    metric & \" (YoY) By Gender\""
            ],
            "lineageTag": "0cd56938-25db-46d3-a6c7-8c2948042283"
          },
          {
            "name": "YoY_%_Avg_Sat",
            "displayFolder": "_TimeIntelligence",
            "expression": [
              "DIVIDE(",
              "    [YoY_Avg_Sat],",
              "    [PY_Avg_Sat],",
              "    0",
              ")"
            ],
            "formatString": "#,##0.00 %",
            "lineageTag": "adf26e28-c78f-484e-8198-755b6e54dac3"
          },
          {
            "name": "Title_Admit",
            "displayFolder": "_Formatting",
            "expression": [
              "",
              "VAR metric = SELECTEDVALUE(Metrics[Metric])",
              "",
              "RETURN ",
              "    metric & \" By Patient Admit Status\""
            ],
            "lineageTag": "891455ba-52d5-466b-9b94-04f9ae495054"
          },
          {
            "name": "Title_Age",
            "displayFolder": "_Formatting",
            "expression": [
              "",
              "VAR metric = SELECTEDVALUE(Metrics[Metric])",
              "",
              "RETURN ",
              "    metric & \" By Age\""
            ],
            "lineageTag": "2afefb21-cf3f-47f4-93ed-6315ca764b6b"
          },
          {
            "name": "Title_Department",
            "displayFolder": "_Formatting",
            "expression": [
              "",
              "VAR metric = SELECTEDVALUE(Metrics[Metric])",
              "",
              "RETURN ",
              "    metric & \" By Department\""
            ],
            "lineageTag": "af34cfa4-af81-4e8c-9f30-4e830a291da7"
          },
          {
            "name": "Title_Gender",
            "displayFolder": "_Formatting",
            "expression": [
              "",
              "VAR metric = SELECTEDVALUE(Metrics[Metric])",
              "",
              "RETURN ",
              "    metric & \" By Gender\""
            ],
            "lineageTag": "f652e024-3ddd-4220-a80b-066dfca23bd6"
          },
          {
            "name": "Title_Race",
            "displayFolder": "_Formatting",
            "expression": [
              "",
              "VAR metric = SELECTEDVALUE(Metrics[Metric])",
              "",
              "RETURN ",
              "    metric & \" By Patient Race\""
            ],
            "lineageTag": "5f4f1f1b-d372-4856-8ff9-b4fd266af049"
          },
          {
            "name": "SM_By_Gender_And_Admit",
            "displayFolder": "_Formatting",
            "expression": "SELECTEDVALUE(Metrics[Metric]) & \" by Admit Status and Gender\"",
            "formatString": "#,0",
            "lineageTag": "d32b47b1-72ba-4b83-8ec3-63c6baf73971"
          },
          {
            "name": "Title_YoY_Gender_Admit",
            "displayFolder": "_Formatting",
            "expression": [
              "",
              "VAR metric = SELECTEDVALUE(Metrics[Metric])",
              "",
              "RETURN ",
              "    metric & \" (YoY) By Admit Status and Gender\""
            ],
            "lineageTag": "b0fca535-3546-4f06-a769-338889e4431c"
          },
          {
            "name": "Title_Trend_Select_With_PY",
            "displayFolder": "_Formatting",
            "expression": [
              "",
              "VAR metric = SELECTEDVALUE(Metrics[Metric])",
              "",
              "VAR trend_score = ",
              "    SWITCH(",
              "        metric,",
              "        \"Satisfaction Score\", [Trend_Satisfaction],",
              "        \"Wait Time\", [Trend_Wait_Times],",
              "        \"Patient Count\", [Trend_Patient_Count]",
              "    )",
              "",
              "VAR direction = IF(trend_score >= 0, \"Up\", \"Down\")",
              "",
              "VAR output = ",
              "    SWITCH(",
              "        metric,",
              "        \"Satisfaction Score\", metric & \" With PY (Trending \" & direction & \")\",",
              "        \"Wait Time\", metric & \" With PY (Trending \" & direction & \")\",",
              "        \"Patient Count\", metric & \" With PY (Trending \" & direction & \")\"",
              "    )",
              "",
              "RETURN ",
              "    output"
            ],
            "lineageTag": "9c7c4546-f7ac-40e4-844d-c96d5889cf7e"
          },
          {
            "name": "SM_By_Dim",
            "displayFolder": "_Formatting",
            "expression": "SELECTEDVALUE(Metrics[Metric]) & \" by \" & [Selected_Dimension]",
            "formatString": "#,0",
            "lineageTag": "4b61005b-4db1-499f-b90f-a01307f0507f"
          },
          {
            "name": "Test_Measure",
            "expression": "1",
            "formatString": "0",
            "lineageTag": "746f5194-c999-466b-b940-7e52b0ca45bd"
          },
          {
            "name": "Total_Wait_Time",
            "expression": "SUM('Hospital_Data'[patient_waittime])",
            "formatString": "0",
            "lineageTag": "3fbf6b38-d7d8-48d9-8c9e-028b46fc7619"
          },
          {
            "name": "CY Patient Count",
            "displayFolder": "__TI Testing",
            "expression": "[Count_Patients]",
            "formatString": "0",
            "lineageTag": "8229b170-c084-438e-afc1-9aabe51be903"
          },
          {
            "name": "PY Patient Count",
            "displayFolder": "__TI Testing",
            "expression": [
              "",
              "CALCULATE(",
              "    [Count_Patients],",
              "    DATEADD(Calendar[Date], -1, YEAR)",
              ")"
            ],
            "formatString": "0",
            "lineageTag": "2cec9ea3-d9d2-443e-b870-550f32bc875b"
          },
          {
            "name": "CY YTD Patient Count",
            "displayFolder": "__TI Testing",
            "expression": [
              "",
              "CALCULATE(",
              "    [Count_Patients],",
              "    DATESYTD( Calendar[Date] )",
              ")"
            ],
            "formatString": "0",
            "lineageTag": "1d76ebbc-7661-4ab8-b3a9-bfd6716813c2"
          },
          {
            "name": "PY YTD Patient Count",
            "displayFolder": "__TI Testing",
            "expression": [
              "",
              "CALCULATE(",
              "    [Count_Patients],",
              "    DATESYTD( DATEADD( Calendar[Date], - 1, YEAR ) )",
              ")"
            ],
            "formatString": "0",
            "lineageTag": "3c32cc8e-f125-4cfd-8214-1075a030af4b"
          },
          {
            "name": "_measurekiller_test_measure",
            "displayFolder": "_Formatting",
            "expression": "[SM_By_Dept]",
            "lineageTag": "17657104-8542-4dda-9db2-cdf9d0356675"
          }
        ],
        "partitions": [
          {
            "name": "_Measures",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText(\"i44FAA==\", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [Column1 = _t]),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(Source,{{\"Column1\", type text}})",
                "in",
                "    #\"Changed Type\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "Metrics",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "Metric",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "726bbdb4-7f7c-4793-957c-527f0b6493ec",
            "sourceColumn": "Metric",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "0c34a9f0-7a3c-4a4c-b786-07e13168309d",
        "partitions": [
          {
            "name": "Metrics",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText(\"i45WCk4sySxOS0wuyczPUwhOzi9KVYrViVYKT8wsUQjJzIXwAoCKUvNKFJzzS/NKlGJjAQ==\", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [Metric = _t]),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(Source,{{\"Metric\", type text}})",
                "in",
                "    #\"Changed Type\""
              ],
              "type": "m"
            }
          }
        ]
      }
    ]
  }
}